version: "3"

services:
  api-source-etl-scripts-twitter:
    build: .
    container_name: "api-source-etl-scripts-twitter"
    command: "python main.py twitter"
    env_file:
      - ./app/.env
    volumes:
      - ./app:/app

  api-source-etl-scripts-csv:
    build: .
    container_name: "api-source-etl-scripts-csv"
    command: "python main.py csv"
    env_file:
      - ./app/.env
    volumes:
      - ./app:/app

  logstash-service:
    build: ./logstash/
    command: logstash -f /logstash.conf
    container_name: logstash-service-etl
    env_file:
      - ./app/.env
    volumes:
      - ./app/app.log:/app.log:ro
      - ./logstash/logstash.conf:/logstash.conf
