version: "3"

services:
  api-source-etl-scripts:
    build: .
    container_name: "api-source-etl-scripts-${mode}"
    command: "python main.py ${mode}"
    env_file:
      - ./app/.env
    volumes:
      - ./app:/app

  logstash-service:
    build: ./logstash/
    command: logstash -f /logstash.conf
    container_name: logstash-service-etl-${mode}
    env_file:
      - ./app/.env
    volumes:
      - ./app/app.log:/app.log:ro
      - ./logstash/logstash.conf:/logstash.conf
